# -*- coding: utf-8 -*-
"""Project 2 Intern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136wdtsrmGteKewxCoci_IcM31I0W2dlN
"""

import pandas as pd
import numpy as np

print("Setup Successful")

from google.colab import files

uploaded = files.upload()

import pandas as pd

file_name = list(uploaded.keys())[0]

print("Uploaded file:", file_name)

import pandas as pd

df = pd.read_csv("Atlantic_South_Korea.csv", encoding='latin1')

print("Dataset Loaded Successfully")

df.head()

df.shape

df.columns

df.info()

df.isnull().sum()

df.duplicated().sum()

df.describe()

# Create a copy of the dataset
df_clean = df.copy()

# Convert date column to datetime format
df_clean['date'] = pd.to_datetime(df_clean['date'])

# Remove duplicate rows
df_clean = df_clean.drop_duplicates()

print("Rows after cleaning:", len(df_clean))

df_clean.info()

print("Unique Songs :", df_clean['song'].nunique())

print("Unique Artists :", df_clean['artist'].nunique())

print("Album Types :", df_clean['album_type'].unique())

print("Date Range Start :", df_clean['date'].min())

print("Date Range End :", df_clean['date'].max())

df_clean[['song','artist']].drop_duplicates().head(20)

df_clean['album_type'].value_counts()

song_presence = (
    df_clean.groupby(['song', 'artist'])
    .size()
    .reset_index(name='days_on_chart')
)

song_presence.head()

song_presence.sort_values(
    by='days_on_chart',
    ascending=False
).head(20)

print("Average Days on Chart:",
      round(song_presence['days_on_chart'].mean(),2))

df_sorted = df_clean.sort_values(['song', 'date'])

df_sorted['prev_song'] = df_sorted['song'].shift(1)

df_sorted['is_new_streak'] = (
    df_sorted['song'] != df_sorted['prev_song']
)

reentry = df_sorted.groupby(['song', 'artist'])['is_new_streak'].sum().reset_index()

reentry = reentry.rename(columns={'is_new_streak': 'reentry_count'})

reentry.sort_values('reentry_count', ascending=False).head(20)

reentry.describe()

df_re = df_clean.copy()

# Sort properly for time analysis
df_re = df_re.sort_values(['song', 'date'])

# Check if song was present previous day
df_re['prev_presence'] = df_re.groupby('song')['position'].shift(1)

# If previous is NaN → first entry
df_re['is_first_entry'] = df_re['prev_presence'].isna()

# Re-entry happens when song appears again after missing days
df_re['is_reentry'] = (
    (df_re['is_first_entry'] == False) &
    (df_re['prev_presence'].isna())
)

# Correct method: detect gaps in presence
df_re['was_present_before'] = df_re.groupby('song')['date'].diff().dt.days > 1

df_re['reentry_flag'] = (
    df_re['was_present_before'].fillna(False)
)

reentry_final = df_re.groupby(['song','artist'])['reentry_flag'].sum().reset_index()

reentry_final.rename(columns={'reentry_flag':'reentry_count'}, inplace=True)

reentry_final.sort_values('reentry_count', ascending=False).head(20)

momentum_df = df_clean.copy()

# Merge re-entry data
momentum_df = momentum_df.merge(
    reentry_final,
    on=['song','artist'],
    how='left'
)

momentum_df['reentry_count'] = momentum_df['reentry_count'].fillna(0)

# Create song-level metrics
song_metrics = momentum_df.groupby(['song','artist']).agg(
    avg_popularity=('popularity','mean'),
    total_days=('date','count'),
    reentry_count=('reentry_count','max')
).reset_index()

# Normalize simple scores
song_metrics['momentum_score'] = (
    song_metrics['avg_popularity'] * 0.5 +
    song_metrics['total_days'] * 0.3 +
    song_metrics['reentry_count'] * 10
)

song_metrics.sort_values('momentum_score', ascending=False).head(20)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

song_metrics_scaled = song_metrics.copy()

song_metrics_scaled[['avg_popularity','total_days','reentry_count']] = scaler.fit_transform(
    song_metrics_scaled[['avg_popularity','total_days','reentry_count']]
)

song_metrics_scaled['momentum_score_final'] = (
    song_metrics_scaled['avg_popularity'] * 0.5 +
    song_metrics_scaled['total_days'] * 0.3 +
    song_metrics_scaled['reentry_count'] * 0.2
)

song_metrics_scaled.sort_values('momentum_score_final', ascending=False).head(20)

import plotly.io as pio
pio.renderers.default = "colab"

!pip install plotly

import plotly.express as px

top_songs = song_metrics_scaled.sort_values(
    'momentum_score_final',
    ascending=False
).head(15)

fig = px.bar(
    top_songs,
    x='momentum_score_final',
    y='song',
    color='artist',
    orientation='h',
    title='Top 15 Songs by Momentum Score'
)

fig.show()

fig = px.histogram(
    reentry_final,
    x='reentry_count',
    nbins=20,
    title='Distribution of Song Re-entry Frequency'
)

fig.show()

song_album_type = df_clean[['song', 'artist', 'album_type']].drop_duplicates()
song_metrics_scaled = song_metrics_scaled.merge(
    song_album_type,
    on=['song', 'artist'],
    how='left'
)

album_type_score = (
    song_metrics_scaled
    .groupby('album_type')['momentum_score_final']
    .mean()
    .reset_index()
)

album_type_score

fig = px.bar(
    album_type_score,
    x='album_type',
    y='momentum_score_final',
    title='Average Momentum Score by Album Type',
    text='momentum_score_final'
)

fig.show()

song_explicit_info = df_clean[['song', 'artist', 'is_explicit']].drop_duplicates()
song_metrics_scaled = song_metrics_scaled.merge(
    song_explicit_info,
    on=['song', 'artist'],
    how='left'
)

explicit_score = (
    song_metrics_scaled
    .groupby('is_explicit')['momentum_score_final']
    .mean()
    .reset_index()
)

explicit_score

fig = px.bar(
    explicit_score,
    x='is_explicit',
    y='momentum_score_final',
    title='Momentum Score by Explicit Content',
    text='momentum_score_final'
)

fig.show()

fandom_score = (
    song_metrics_scaled
    .groupby('artist')
    .agg(
        avg_momentum=('momentum_score_final', 'mean'),
        total_re_entries=('reentry_count', 'sum')
    )
    .reset_index()
)

fandom_score.head()

top_fandom = fandom_score.sort_values(
    by='total_re_entries',
    ascending=False
).head(15)

fig = px.bar(
    top_fandom,
    x='total_re_entries',
    y='artist',
    orientation='h',
    title='Top Artists by Re-entry Frequency'
)

fig.show()

#Histogram of Momentum Scores
import plotly.express as px

fig = px.histogram(
    song_metrics_scaled,
    x='momentum_score_final',
    nbins=30,
    title='Distribution of Momentum Scores',
    labels={'momentum_score_final': 'Momentum Score'},
    marginal='box'
)

fig.show()

#Histogram of Momentum Scores
#Basic Statistics
song_metrics_scaled['momentum_score_final'].describe()

#Categorize Momentum Levels
def momentum_level(score):
    if score >= 0.75:
        return "High"
    elif score >= 0.40:
        return "Medium"
    else:
        return "Low"

song_metrics_scaled['Momentum_Level'] = song_metrics_scaled['momentum_score_final'].apply(momentum_level)

song_metrics_scaled[['momentum_score_final', 'Momentum_Level']].head()

#Count Songs in Each Category
momentum_counts = (
    song_metrics_scaled['Momentum_Level']
    .value_counts()
    .reset_index()
)

momentum_counts.columns = ['Momentum Level', 'Number of Songs']

momentum_counts

#Visualize the Categories
fig = px.pie(
    momentum_counts,
    names='Momentum Level',
    values='Number of Songs',
    title='Distribution of Songs by Momentum Level'
)

fig.show()

#Rank Recovery Speed Analysis
#Sort The Dataset
rank_df = df_clean.copy()

rank_df['date'] = pd.to_datetime(rank_df['date'], dayfirst=True)

rank_df = rank_df.sort_values(['song', 'date'])

#Previous Rank
rank_df['previous_position'] = rank_df.groupby('song')['position'].shift(1)

rank_df[['song', 'date', 'position', 'previous_position']].head()

#Calculate Rank Recovery
rank_df['rank_recovery'] = rank_df['previous_position'] - rank_df['position']

rank_df[['song', 'position', 'previous_position', 'rank_recovery']].head()

#Average Recovery By Song
recovery_score = (
    rank_df.groupby('song')['rank_recovery']
    .mean()
    .reset_index()
)

recovery_score = recovery_score.sort_values(
    by='rank_recovery',
    ascending=False
)

recovery_score.head(15)

#Visualization
fig = px.bar(
    recovery_score.head(15),
    x='rank_recovery',
    y='song',
    orientation='h',
    title='Top 15 Songs by Average Rank Recovery'
)

fig.show()

kpi = {}

# Total unique songs
kpi['Total Songs'] = song_metrics_scaled['song'].nunique()

# Total artists
kpi['Total Artists'] = song_metrics_scaled['artist'].nunique()

# Average Momentum Score
kpi['Average Momentum Score'] = round(
    song_metrics_scaled['momentum_score_final'].mean(), 3
)

# Maximum Momentum Score
kpi['Highest Momentum Score'] = round(
    song_metrics_scaled['momentum_score_final'].max(), 3
)

# Average Popularity
kpi['Average Popularity'] = round(
    song_metrics_scaled['avg_popularity'].mean(), 2
)

# Total Re-entries
kpi['Total Re-entries'] = int(
    song_metrics_scaled['reentry_count'].sum()
)

kpi

kpi_df = pd.DataFrame(
    kpi.items(),
    columns=['KPI', 'Value']
)

kpi_df

#KPI Visualization
fig = px.bar(
    kpi_df,
    x='KPI',
    y='Value',
    text='Value',
    title='Project Key Performance Indicators'
)

fig.show()

#Correlation Analysis
correlation_df = song_metrics_scaled[[
    'avg_popularity',
    'total_days',
    'reentry_count',
    'momentum_score_final'
]]

correlation_df.corr()

import plotly.express as px

corr = correlation_df.corr()

fig = px.imshow(
    corr,
    text_auto=True,
    color_continuous_scale='Viridis',
    title='Correlation Heatmap'
)

fig.show()

#Top 10 Momentum Songs
top_songs = (
    song_metrics_scaled
    .sort_values(
        'momentum_score_final',
        ascending=False
    )
    [['song', 'artist', 'momentum_score_final']]
    .drop_duplicates()
    .head(10)
)

top_songs

fig = px.bar(
    top_songs,
    x='momentum_score_final',
    y='song',
    color='artist',
    orientation='h',
    title='Top 10 Songs by Momentum Score'
)

fig.show()

song_metrics_scaled.to_csv("Final_SouthKorea_Analysis.csv", index=False)
print("CSV Saved Successfully!")

print(song_metrics_scaled.columns.tolist())

print(df.columns.tolist())

for col in song_metrics_scaled.columns:
    print(col)